version: "3.0"
services:
  postgres:
    container_name: "postgres_container"
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: "123"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "mailbox"
    ports:
      - "5432:5432"
