"""add datetime field to Mail model

Revision ID: a16454365785
Revises: 
Create Date: 2023-02-08 12:42:24.477345

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a16454365785'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mails')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('surname', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('email', name='users_email_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('mails',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('mail_body', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('from_email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('to_email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['from_email'], ['users.email'], name='mails_from_email_fkey'),
    sa.ForeignKeyConstraint(['to_email'], ['users.email'], name='mails_to_email_fkey'),
    sa.PrimaryKeyConstraint('id', name='mails_pkey')
    )
    # ### end Alembic commands ###
